import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {createAction,executeAction,getActions,updateAction} from "../../services/action.service";

export default function ActionsPage(){
  const [name,setName]=useState(""),[type,setType]=useState("API"),queryClient=useQueryClient();
  const query=useQuery({queryKey:["actions"],queryFn:getActions}),refresh=()=>queryClient.invalidateQueries({queryKey:["actions"]});
  const add=useMutation({mutationFn:createAction,onSuccess:refresh}),change=useMutation({mutationFn:({id,payload})=>updateAction(id,payload),onSuccess:refresh}),run=useMutation({mutationFn:executeAction,onSuccess:refresh});
  return <main className="min-h-full bg-gradient-to-br from-[#071426] via-[#0B1F3A] to-[#142B52] p-5 text-white md:p-8"><h1 className="text-3xl font-bold">Actions</h1><p className="mt-1 text-slate-400">Manage governed enterprise actions and automations</p><form onSubmit={event=>{event.preventDefault();add.mutate({name,type,permissions:{}});setName("")}} className="mt-6 flex max-w-xl gap-3"><input value={name} onChange={event=>setName(event.target.value)} placeholder="Action name" required className="flex-1 rounded-lg border border-white/10 bg-white/5 px-3 py-2"/><select value={type} onChange={event=>setType(event.target.value)} className="rounded-lg bg-white/5 px-3"><option>API</option><option>Database</option><option>Integration</option></select><button className="rounded-lg bg-violet-600 px-4">Create</button></form><div className="mt-6 overflow-x-auto rounded-2xl border border-white/10 bg-white/5"><table className="w-full min-w-[750px] text-left text-sm"><thead className="text-slate-400"><tr>{["Action","Provider","Risk","Approval","Status","Usage","Controls"].map(label=><th key={label} className="p-4">{label}</th>)}</tr></thead><tbody>{query.data?.map(action=><tr key={action.id} className="border-t border-white/10"><td className="p-4"><strong className="block">{action.display_name||action.name}</strong><small className="text-slate-400">{action.name}</small></td><td className="p-4 capitalize">{action.provider||action.type}</td><td className="p-4 capitalize">{action.risk_level||"—"}</td><td className="p-4">{action.approval_required?"Required":"No"}</td><td className="p-4 capitalize">{action.status}</td><td className="p-4">{action.usage}</td><td className="p-4"><button onClick={()=>run.mutate(action.id)} disabled={action.status!=="enabled"} className="mr-3 text-emerald-300">Execute</button><button onClick={()=>change.mutate({id:action.id,payload:{status:action.status==="enabled"?"DISABLED":"ENABLED"}})} className="text-amber-300">{action.status==="enabled"?"Disable":"Enable"}</button></td></tr>)}</tbody></table>{!query.isLoading&&!query.data?.length&&<p className="p-8 text-slate-400">No actions registered.</p>}</div></main>
}
