import { useDeferredValue, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { Plus, RefreshCw, Search } from "lucide-react";
import AgentBuilder from "../../components/agents/AgentBuilder";
import { useAgents } from "../../hooks/useAgents";

const statusOptions=["","draft","published","enabled","disabled","archived","error"];
export default function AgentsPage(){const [params,setParams]=useSearchParams(),[builder,setBuilder]=useState(false);const search=useDeferredValue(params.get("search")||"");const query={search,status:params.get("status")||undefined,owner:params.get("owner")||undefined,model:params.get("model")||undefined,environment:params.get("environment")||undefined,include_archived:params.get("archived")==="true",sort:params.get("sort")||"updated_at",direction:params.get("direction")||"desc",page:Number(params.get("page")||1),page_size:Number(params.get("page_size")||10)};const agents=useAgents(query);const data=agents.data||{items:[],total:0,pages:1,page:1};const update=(key,value)=>setParams(current=>{const next=new URLSearchParams(current);value?next.set(key,value):next.delete(key);if(key!=="page")next.set("page","1");return next;});const canCreate=data.items[0]?.permissions?.create!==false;
  return <main className="min-h-full bg-gradient-to-br from-[#071426] via-[#0B1F3A] to-[#142B52] p-4 text-white md:p-8"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Agents</h1><p className="mt-1 text-slate-400">Governed, tenant-scoped AI Agents</p></div><div className="flex gap-2"><button aria-label="Refresh Agents" onClick={()=>agents.refetch()} className="focus-ring rounded-lg border border-white/15 p-2"><RefreshCw size={18} className={agents.isFetching?"animate-spin":""}/></button>{canCreate&&<button onClick={()=>setBuilder(true)} className="focus-ring inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2"><Plus size={16}/>Create Agent</button>}</div></header>
    {builder&&<AgentBuilder onClose={()=>setBuilder(false)} onSaved={()=>{setBuilder(false);agents.refetch();}}/>}
    {!builder&&<><section className="mt-6 grid gap-3 rounded-xl border border-white/10 bg-white/5 p-4 sm:grid-cols-2 xl:grid-cols-7" aria-label="Agent directory filters"><label className="relative xl:col-span-2"><span className="sr-only">Search Agents</span><Search className="absolute left-3 top-3" size={16}/><input aria-label="Search Agents" defaultValue={params.get("search")||""} onChange={e=>update("search",e.target.value)} className="w-full rounded-lg border border-white/10 bg-slate-950/50 py-2 pl-9 pr-3" placeholder="Search name, slug, description"/></label><Select label="Lifecycle" value={query.status||""} onChange={value=>update("status",value)} options={statusOptions}/><input aria-label="Owner filter" value={query.owner||""} onChange={e=>update("owner",e.target.value)} className="rounded-lg border border-white/10 bg-slate-950/50 p-2" placeholder="Owner"/><input aria-label="Model filter" value={query.model||""} onChange={e=>update("model",e.target.value)} className="rounded-lg border border-white/10 bg-slate-950/50 p-2" placeholder="Model"/><Select label="Environment" value={query.environment||""} onChange={value=>update("environment",value)} options={["","development","staging","production"]}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={query.include_archived} onChange={e=>update("archived",e.target.checked?"true":"")}/>Include archived</label><Select label="Sort" value={query.sort} onChange={value=>update("sort",value)} options={["updated_at","name","lifecycle","owner"]}/><Select label="Direction" value={query.direction} onChange={value=>update("direction",value)} options={["desc","asc"]}/></section>
      <DirectoryState query={agents} filtered={Boolean(search||query.status||query.owner||query.model||query.environment)}>{data.items.length>0&&<div className="mt-4 overflow-x-auto rounded-xl border border-white/10"><table className="min-w-[1100px] w-full text-left text-sm"><caption className="sr-only">Agent directory, {data.total} total results</caption><thead className="bg-white/5 text-slate-300"><tr>{["Agent","Lifecycle","Health","Version","Owner","Model","Tools","Knowledge","Last execution","Success","Updated"].map(value=><th scope="col" className="p-3" key={value}>{value}</th>)}</tr></thead><tbody>{data.items.map(agent=><tr key={agent.id} className="border-t border-white/10"><td className="p-3"><Link className="focus-ring font-medium text-violet-300 hover:underline" to={`/agents/${agent.id}?tab=overview`}>{agent.name}</Link><small className="block text-slate-500">{agent.slug}</small></td><td className="p-3 capitalize">{agent.lifecycle_status}</td><td className="p-3 capitalize">{agent.operational_health}</td><td className="p-3">{agent.published_version||"—"}</td><td className="p-3">{agent.owner_id}</td><td className="p-3">{agent.model||"—"}</td><td className="p-3">{agent.tool_count}</td><td className="p-3">{agent.knowledge_count}</td><td className="p-3">{agent.last_execution_at?new Date(agent.last_execution_at).toLocaleString():"Never"}</td><td className="p-3">{agent.success_rate==null?"—":`${agent.success_rate}%`}</td><td className="p-3">{new Date(agent.updated_at).toLocaleString()}</td></tr>)}</tbody></table></div>}</DirectoryState>
      <nav className="mt-4 flex flex-wrap items-center justify-between gap-3" aria-label="Agent directory pagination"><span className="text-sm text-slate-400">{data.total} results · page {data.page} of {data.pages}</span><div className="flex gap-2"><button aria-label="Previous page" disabled={data.page<=1} onClick={()=>update("page",String(data.page-1))} className="focus-ring rounded-lg border border-white/15 px-3 py-2 disabled:opacity-40">Previous</button><button aria-label="Next page" disabled={data.page>=data.pages} onClick={()=>update("page",String(data.page+1))} className="focus-ring rounded-lg border border-white/15 px-3 py-2 disabled:opacity-40">Next</button><select aria-label="Page size" value={query.page_size} onChange={e=>update("page_size",e.target.value)} className="rounded-lg bg-slate-900 p-2"><option>10</option><option>20</option><option>50</option></select></div></nav></>}
  </main>}
function Select({label,value,onChange,options}){return <label className="text-xs text-slate-400">{label}<select aria-label={`${label} filter`} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-slate-950/50 p-2 text-sm text-white">{options.map(item=><option key={item} value={item}>{item||"All"}</option>)}</select></label>}
function DirectoryState({query,filtered,children}){if(query.isLoading)return <p aria-live="polite" className="mt-8">Loading Agents…</p>;if(query.error){const status=query.error.response?.status;return <section role="alert" className="mt-8 rounded-xl border border-red-400/30 p-5"><h2>{status===401?"Authentication required":status===403?"Permission denied":status>=500?"Server unavailable":"Agents could not be loaded"}</h2><button onClick={()=>query.refetch()} className="mt-3 rounded-lg bg-violet-600 px-4 py-2">Retry</button></section>}if(!query.data?.items?.length)return <section className="mt-8 rounded-xl border border-dashed border-white/15 p-8 text-center"><h2>{filtered?"No Agents match these filters":"No Agents yet"}</h2><p className="text-slate-400">{filtered?"Clear or adjust the directory filters.":"Create a governed Agent to begin."}</p></section>;return children}
