import { useMemo, useState } from "react";
import { Plus } from "lucide-react";
import AgentBuilder from "../../components/agents/AgentBuilder";
import AgentDetails from "../../components/agents/AgentDetails";
import AgentDirectory from "../../components/agents/AgentDirectory";
import { ResourceState } from "../../components/common/ResourceState";
import { useAgents } from "../../hooks/useAgents";

const initial={name:"",purpose:"",description:"",instructions:"",model:"GPT-5.5",memory_enabled:true,capabilities:"",tools:"",knowledge_sources:"",permissions:{"Read Workflows":true,"Execute Actions":true,"Access Audit Logs":true,"Manage Agents":false,"Admin Access":false}};
export default function AgentsPage(){const [view,setView]=useState("directory"),[selected,setSelected]=useState(null),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[form,setForm]=useState(initial);const {query,create}=useAgents();const agents=useMemo(()=> (query.data||[]).filter(a=>`${a.name} ${a.description}`.toLowerCase().includes(search.toLowerCase())&&(status==="all"||a.status===status)),[query.data,search,status]);const agent=agents.find(a=>a.id===selected)||agents[0];const submit=e=>{e.preventDefault();const toList=k=>form[k].split(",").map(x=>x.trim()).filter(Boolean);create.mutate({...form,capabilities:toList("capabilities"),tools:toList("tools"),knowledge_sources:toList("knowledge_sources")},{onSuccess:()=>{setView("directory");setForm(initial)}})};return <main className="min-h-full bg-gradient-to-br from-[#071426] via-[#0B1F3A] to-[#142B52] p-5 text-white md:p-8"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Agents</h1><p className="mt-1 text-slate-400">Manage and monitor your AI workforce</p></div><button onClick={()=>setView("builder")} className="inline-flex items-center gap-2 rounded-lg bg-gradient-to-r from-indigo-500 to-violet-500 px-4 py-2 text-sm font-medium"><Plus size={16}/>Create Agent</button></header><div className="mt-5 flex gap-2"><button onClick={()=>setView("directory")} className={`rounded-lg border px-4 py-2 text-sm ${view==="directory"?"border-violet-400/40 bg-violet-500/15":"border-white/10 text-slate-300"}`}>Agent Directory</button><button onClick={()=>setView("builder")} className={`rounded-lg border px-4 py-2 text-sm ${view==="builder"?"border-violet-400/40 bg-violet-500/15":"border-white/10 text-slate-300"}`}>Agent Builder</button></div>{view==="directory"?<div className="mt-4 grid grid-cols-[minmax(300px,.9fr)_minmax(0,1.25fr)] gap-5 overflow-x-auto"><ResourceState loading={query.isLoading} error={query.error} empty={!query.data?.length} label="agents"><AgentDirectory agents={agents} selected={agent?.id} onSelect={setSelected} search={search} setSearch={setSearch} status={status} setStatus={setStatus}/></ResourceState><AgentDetails agent={agent}/></div>:<AgentBuilder form={form} setForm={setForm} onClose={()=>setView("directory")} onSubmit={submit} pending={create.isPending}/>}</main>}
