const providerModels={openai:["gpt-4.1","gpt-4.1-mini"],bedrock:["amazon.nova-lite-v1:0","anthropic.claude-3-5-sonnet-20241022-v2:0"]};
export default function ChatHeader({agents,agentId,setAgentId,provider,setProvider,model,setModel,workspace,setWorkspace,runtime}){
 const agent=agents.find(item=>item.id===agentId);const controlled=Boolean(agent);const authoritativeProvider=agent?.model_provider||agent?.model_configuration?.provider;const authoritativeModel=agent?.model||agent?.model_configuration?.model;
 return <header className="flex flex-wrap items-center gap-3 border-b border-white/10 bg-[#071426]/80 px-4 py-3"><div className="mr-auto min-w-48"><h1 className="font-semibold">Enterprise Runtime Workspace</h1><p className="text-xs text-slate-500">Live orchestration, tools, approvals, and audit</p></div>
 {[["Workspace",workspace,setWorkspace,["Finance Operations","Engineering","Procurement"]],["Agent",agentId,setAgentId,[{value:"",label:"Auto Select"},...agents.map(item=>({value:item.id,label:`${item.name} · ${item.lifecycle_status} · ${item.operational_health}`}))]]].map(([label,value,setValue,options])=><label key={label} className="text-[10px] uppercase tracking-wide text-slate-500">{label}<select aria-label={label} value={value} onChange={e=>setValue(e.target.value)} className="mt-1 block max-w-52 rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-xs normal-case text-slate-100">{options.map(option=>typeof option==="string"?<option key={option}>{option}</option>:<option key={option.value} value={option.value}>{option.label}</option>)}</select></label>)}
 <label className="text-[10px] uppercase tracking-wide text-slate-500">Provider<select aria-label="Provider" disabled={controlled} value={controlled?authoritativeProvider||provider:provider} onChange={e=>{setProvider(e.target.value);setModel(e.target.value==="automatic"?"automatic":providerModels[e.target.value][0])}} className="mt-1 block rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-xs normal-case text-slate-100 disabled:opacity-60"><option value="automatic">Automatic</option><option value="openai">OpenAI</option><option value="bedrock">AWS Bedrock</option></select></label>
 <label className="text-[10px] uppercase tracking-wide text-slate-500">Model<select aria-label="Model" disabled={controlled||provider==="automatic"} value={controlled?authoritativeModel||model:model} onChange={e=>setModel(e.target.value)} className="mt-1 block max-w-52 rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-xs normal-case text-slate-100 disabled:opacity-60">{controlled?<option>{authoritativeModel}</option>:provider==="automatic"?<option value="automatic">Automatic</option>:providerModels[provider].map(item=><option key={item}>{item}</option>)}</select></label>
 {runtime?.selectedAgent&&<div className="rounded-lg border border-violet-400/20 bg-violet-400/10 px-3 py-2 text-[11px] text-violet-100"><span className="block font-medium">Executing: {runtime.selectedAgent.name}</span><span className="text-violet-300">{runtime.selectedAgent.provider} · {runtime.selectedAgent.model}</span></div>}
 <div className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-2 text-xs text-emerald-300">● Runtime online</div></header>
}
