export default function DynamicFieldRenderer({field,value,onChange,invalid=false}){
  const options=field.options || [];
  const base=`mt-1 w-full rounded-lg border ${invalid?"border-rose-400":"border-white/10"} bg-[#071426] px-3 py-2 text-sm text-slate-100 outline-none focus:border-violet-400`;
  if(field.type==="boolean")return <div className="mt-2 flex gap-2">{[true,false].map(option=><button type="button" key={String(option)} onClick={()=>onChange(option)} className={`rounded-lg border px-4 py-2 text-sm ${value===option?"border-violet-400 bg-violet-500/30":"border-white/10 bg-white/5"}`}>{option?"Yes":"No"}</button>)}</div>;
  if(field.type==="radio")return <div className="mt-2 flex flex-wrap gap-3">{options.map(option=>{const item=typeof option==="string"?{label:option,value:option}:option;return <label key={item.value} className="flex items-center gap-2 text-sm"><input type="radio" name={field.name} required={field.required} checked={value===item.value} onChange={()=>onChange(item.value)}/>{item.label}</label>})}</div>;
  if(field.type==="select"||field.type==="multiselect")return <select multiple={field.type==="multiselect"} required={field.required} className={base} value={value ?? (field.type==="multiselect"?[]:"")} onChange={event=>onChange(field.type==="multiselect"?[...event.target.selectedOptions].map(item=>item.value):event.target.value)}><option value="">Select…</option>{options.map(option=>{const item=typeof option==="string"?{label:option,value:option}:option;return <option key={item.value} value={item.value}>{item.label}</option>})}</select>;
  if(field.type==="date-range")return <div className="mt-1 grid grid-cols-2 gap-2"><input aria-label={`${field.label} from`} type="date" className={base} value={value?.from||""} onChange={e=>onChange({...value,from:e.target.value})}/><input aria-label={`${field.label} to`} type="date" className={base} value={value?.to||""} onChange={e=>onChange({...value,to:e.target.value})}/></div>;
  if(field.type==="textarea"||field.type==="json")return <textarea required={field.required} className={base} rows={3} value={typeof value==="string"?value:""} onChange={e=>onChange(e.target.value)}/>;
  const type={integer:"number",datetime:"datetime-local",secret:"password",uri:"url",url:"url",string:"text"}[field.type]||field.type||"text";
  return <input required={field.required} className={base} type={type} value={value??""} onChange={e=>onChange(type==="number"?Number(e.target.value):e.target.value)}/>;
}
