import {useState} from "react";
const tabs=["Runtime Flow","Execution Plan","Context","Agent","Tools","Actions","Logs","Metrics","Sources"];
const Empty=({children})=><p className="rounded-xl border border-dashed border-white/10 p-4 text-sm text-slate-500">{children}</p>;
export default function ExecutionInspector({runtime}){
 const [tab,setTab]=useState("Runtime Flow");
 const rows=tab==="Tools"?runtime.tools:tab==="Actions"?runtime.actions:tab==="Logs"?runtime.logs:runtime.steps;
 return <aside className="hidden w-[360px] shrink-0 border-l border-white/10 bg-[#071426]/85 xl:flex xl:flex-col"><div className="flex gap-1 overflow-x-auto border-b border-white/10 p-3">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-[11px] ${tab===item?"bg-violet-500/20 text-violet-300":"text-slate-400"}`}>{item}</button>)}</div>
 <div className="flex-1 overflow-y-auto p-4"><div className="mb-4 rounded-xl border border-white/10 bg-white/5 p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-wide text-slate-500">Runtime status</p><p className="mt-1 font-medium">{runtime.status}</p></div><span className={`h-2 w-2 rounded-full ${runtime.status==="COMPLETED"?"bg-emerald-400":runtime.status.startsWith("WAITING")?"bg-amber-400":runtime.status==="FAILED"?"bg-rose-400":"bg-blue-400 animate-pulse"}`}/></div><p className="mt-2 truncate text-[10px] text-slate-600" title={runtime.executionId}>{runtime.executionId||"No active execution"}</p></div>
 {tab==="Execution Plan"?(runtime.plan.length?<div className="space-y-2">{runtime.plan.map((step,index)=><div key={step.id||index} className="rounded-xl border border-white/10 bg-white/5 p-3"><p className="text-xs text-violet-300">Step {index+1} · {step.type}</p><p className="mt-1 text-sm font-medium">{step.name}</p><p className="mt-1 text-xs text-slate-400">{step.description}</p><Data values={{Dependency:(step.dependencies||[]).join(", ")||"None",Capability:step.required_capability||"—",Resolved:step.resolved_tool||step.resolved_action||step.tool||"—",Status:step.status||"pending"}}/></div>)}</div>:<Empty>No execution plan has been emitted.</Empty>):tab==="Context"?<Data values={{Conversation:runtime.executionId?"Active conversation":"—",Workspace:runtime.metrics.workspace||"Finance Operations",Provider:runtime.metrics.provider||"—",Model:runtime.metrics.model||"—"}}/>:tab==="Agent"?(runtime.selectedAgent?<><Data values={{Name:runtime.selectedAgent.name,"Selection mode":runtime.selectedAgent.selectionMode||"automatic",Confidence:runtime.selectedAgent.selectionMode==="user_selected"?"User selected":runtime.selectedAgent.confidence==null?"—":`${Math.round(runtime.selectedAgent.confidence*100)}%`,Reason:runtime.selectedAgent.reason||"—",Provider:runtime.selectedAgent.provider||runtime.metrics.provider||"—",Model:runtime.selectedAgent.model||runtime.metrics.model||"—",Capabilities:(runtime.selectedAgent.capabilities||[]).join(", ")||"—","Assigned tools":(runtime.selectedAgent.tools||[]).join(", ")||"—","Knowledge sources":runtime.selectedAgent.knowledgeSourceCount??"—"}}/>{runtime.candidates.length>1&&<div className="mt-3 space-y-2"><p className="text-xs uppercase tracking-wide text-slate-500">Other candidates</p>{runtime.candidates.slice(1).map(candidate=><div key={candidate.agent_id} className="rounded-lg bg-white/5 p-3 text-xs"><div className="flex justify-between"><b>{candidate.name}</b><span>{Math.round(candidate.confidence*100)}%</span></div><p className="mt-1 text-slate-500">{candidate.reason}</p></div>)}</div>}</>:<Empty>No persisted agent has been selected.</Empty>):tab==="Metrics"?<Data values={{Duration:formatMetric(runtime.metrics.duration_ms,"ms"),Tokens:tokenTotal(runtime.metrics.token_usage),"Provider latency":formatMetric(runtime.metrics.provider_latency_ms,"ms"),"Estimated cost":formatCost(runtime.metrics.estimated_cost),"Actual cost":formatCost(runtime.metrics.actual_cost),Provider:runtime.metrics.provider||"—",Model:runtime.metrics.model||"—"}}/>:tab==="Sources"?(runtime.sources.length?<div className="space-y-2">{runtime.sources.map((source,index)=><div key={source.source_id||index} className="rounded-xl border border-white/10 bg-white/5 p-3"><p className="text-sm font-medium">{source.name||"Knowledge source"}</p><p className="text-xs text-slate-500">{source.type}</p></div>)}</div>:<Empty>No knowledge sources were used.</Empty>):<EventRows rows={rows}/>}</div></aside>
}
function EventRows({rows}){return rows.length?<div className="space-y-2">{rows.map((item,index)=><div key={item.step_id||item.event_id||`${item.type}-${item.name}-${index}`} className="rounded-xl border border-white/10 bg-white/5 p-3"><div className="flex justify-between gap-2"><p className="text-sm font-medium">{item.name||item.type}</p><span className="text-[9px] uppercase text-emerald-300">{item.status}</span></div><p className="mt-1 text-xs text-slate-400">{item.description}</p>{item.duration_ms!=null&&<p className="mt-1 text-[10px] text-slate-600">{Math.round(item.duration_ms)} ms</p>}</div>)}</div>:<Empty>No events in this category.</Empty>}
function Data({values}){return <div className="space-y-2">{Object.entries(values).map(([key,value])=><div key={key} className="flex items-start justify-between gap-3 rounded-lg bg-white/5 p-3 text-xs"><span className="text-slate-500">{key}</span><span className="max-w-[190px] break-words text-right text-slate-200">{String(value??"—")}</span></div>)}</div>}
const tokenTotal=value=>value?.total_tokens??value?.total??"—";const formatMetric=(value,unit)=>value==null?"—":`${Math.round(Number(value))} ${unit}`;const formatCost=value=>value==null?"—":`$${Number(value).toFixed(4)}`;
