global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "enterprise-ai-backend"

    metrics_path: /metrics

    static_configs:
      - targets:
          - enterprise-ai-alb-844382135.us-east-1.elb.amazonaws.com