"""make task agent nullable

Revision ID: 57d2ef723b0b
Revises: 4c798e1da4ad
Create Date: 2026-07-27 18:29:44.346084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d2ef723b0b'
down_revision: Union[str, Sequence[str], None] = '4c798e1da4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'agent',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'agent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
