"""add Tool SDK persistence
Revision ID: d7e9f1a3b5c7
Revises: c6e8f0a2b4d6
"""
from alembic import op
import sqlalchemy as sa
revision="d7e9f1a3b5c7"; down_revision="c6e8f0a2b4d6"; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("tool_definitions", sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(120),nullable=False),sa.Column("name",sa.String(100),nullable=False),sa.Column("display_name",sa.String(120),nullable=False),sa.Column("description",sa.Text,nullable=False),sa.Column("category",sa.String(80),nullable=False),sa.Column("provider",sa.String(80),nullable=False),sa.Column("version",sa.String(40),nullable=False),sa.Column("input_schema",sa.JSON,nullable=False),sa.Column("output_schema",sa.JSON,nullable=True),sa.Column("permissions",sa.JSON,nullable=False),sa.Column("tags",sa.JSON,nullable=False),sa.Column("risk_level",sa.String(20),nullable=False),sa.Column("enabled",sa.Boolean,nullable=False),sa.Column("active",sa.Boolean,nullable=False),sa.Column("deprecated",sa.Boolean,nullable=False),sa.Column("registration_source",sa.String(120),nullable=False),sa.Column("configuration_state",sa.String(30),nullable=False),sa.Column("created_by",sa.String(120),nullable=False),sa.Column("updated_by",sa.String(120),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","name","version",name="uq_tool_tenant_name_version"))
    op.create_index("ix_tools_catalog","tool_definitions",["tenant_id","provider","category","enabled"])
    op.create_table("tool_executions", sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(120),nullable=False),sa.Column("tool_name",sa.String(100),nullable=False),sa.Column("tool_version",sa.String(40),nullable=False),sa.Column("actor_id",sa.String(160),nullable=False),sa.Column("agent_id",sa.String(160),nullable=True),sa.Column("status",sa.String(30),nullable=False),sa.Column("correlation_id",sa.String(100),nullable=False),sa.Column("trace_id",sa.String(100),nullable=True),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("finished_at",sa.DateTime(timezone=True)),sa.Column("duration_ms",sa.Float),sa.Column("input_summary",sa.JSON,nullable=False),sa.Column("output_summary",sa.JSON),sa.Column("error_code",sa.String(80)),sa.Column("error_message",sa.String(500)),sa.Column("retry_count",sa.Integer,nullable=False),sa.Column("idempotency_key",sa.String(160)),sa.Column("provider_request_id",sa.String(160)),sa.UniqueConstraint("tenant_id","tool_name","idempotency_key",name="uq_tool_idempotency"))
    op.create_index("ix_tool_execution_history","tool_executions",["tenant_id","started_at","status"]); op.create_index("ix_tool_execution_correlation","tool_executions",["correlation_id"])
    op.create_table("integration_configurations", sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(120),nullable=False),sa.Column("provider",sa.String(80),nullable=False),sa.Column("display_name",sa.String(120),nullable=False),sa.Column("base_url",sa.String(500)),sa.Column("account_identifier",sa.String(255)),sa.Column("auth_method",sa.String(80)),sa.Column("secret_reference",sa.String(500)),sa.Column("safe_metadata",sa.JSON,nullable=False),sa.Column("enabled",sa.Boolean,nullable=False),sa.Column("health_status",sa.String(30),nullable=False),sa.Column("health_message",sa.String(500)),sa.Column("last_verified_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","provider",name="uq_integration_tenant_provider"))
    op.create_index("ix_integration_status","integration_configurations",["tenant_id","enabled","health_status"])
def downgrade():
    op.drop_table("integration_configurations"); op.drop_table("tool_executions"); op.drop_table("tool_definitions")
