import { useMemo, useState } from "react";
import { Check, ChevronLeft, ChevronRight, X } from "lucide-react";
import { createAgent, getAgentOptions, lifecycleAgent, saveAssignments } from "../../services/agentService";
import { useQuery } from "@tanstack/react-query";

const steps=["Basics","Instructions & Model","Tools","Knowledge","Access & Governance","Review"];
const field="mt-1 w-full rounded-lg border border-white/15 bg-slate-950/60 px-3 py-2 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-400/30";
const initial={name:"",slug:"",description:"",instructions:"",provider:"configured",model:"model-a",planner:"default",tools:[],knowledge:[],access:[],maxSteps:20,timeout:120,costLimit:"",risk:"read",environments:["production"]};

export default function AgentBuilder({onClose,onSaved}){
  const [step,setStep]=useState(0),[form,setForm]=useState(initial),[errors,setErrors]=useState({}),[general,setGeneral]=useState(""),[saving,setSaving]=useState(false);
  const {data:options,isLoading,error}=useQuery({queryKey:["agent-options"],queryFn:getAgentOptions});
  const dirty=JSON.stringify(form)!==JSON.stringify(initial);
  const set=(key,value)=>setForm(current=>({...current,[key]:value}));
  const validate=()=>{const next={};if(step===0&&form.name.trim().length<2)next.name="Enter at least two characters.";if(step===1&&!form.instructions.trim())next.instructions="Instructions are required before publishing.";if(step===1&&!form.model)next.model="Select a supported model.";setErrors(next);return !Object.keys(next).length;};
  const move=delta=>{if(delta>0&&!validate())return;setStep(value=>Math.max(0,Math.min(steps.length-1,value+delta)));};
  const close=()=>{if(!dirty||window.confirm("Discard unsaved Agent changes?"))onClose();};
  const toggle=(key,value)=>set(key,form[key].includes(value)?form[key].filter(item=>item!==value):[...form[key],value]);
  const payload=useMemo(()=>({name:form.name,slug:form.slug||undefined,description:form.description,instructions:form.instructions,model_configuration:{provider:form.provider,model:form.model},planner_configuration:{name:form.planner},execution_limits:{max_steps:Number(form.maxSteps),timeout_seconds:Number(form.timeout),cost_limit:form.costLimit===""?null:Number(form.costLimit),risk_limit:form.risk,environments:form.environments},tool_discovery_configuration:{mode:"assigned_only"},change_note:"Created in Agent Builder"}),[form]);
  async function save(publish=false){if(!validate()){setStep(form.name?1:0);return;}setSaving(true);setGeneral("");try{const agent=await createAgent(payload);if(form.tools.length)await saveAssignments(agent.id,"tools",form.tools.map(name=>({tool_name:name,version_restriction:"active",assignment_action:"execute",enabled:true,risk_mode:options.tools.find(item=>item.name===name)?.risk||"read",approval_required:false})));if(form.knowledge.length)await saveAssignments(agent.id,"knowledge",form.knowledge.map(id=>({knowledge_source_id:id,access_mode:"retrieve",readiness_required:true,enabled:true})));if(form.access.length)await saveAssignments(agent.id,"access",form.access);const saved=publish?await lifecycleAgent(agent.id,"publish",agent.lock_version,{change_note:"Published from Agent Builder"}):agent;onSaved(saved,{published:publish});}catch(requestError){const detail=requestError.response?.data?.detail;setGeneral(detail?.message||"The Agent could not be saved. Review the fields and retry.");}finally{setSaving(false);}}
  if(isLoading)return <section aria-live="polite" className="panel-state">Loading builder options…</section>;
  if(error)return <section role="alert" className="panel-state error">Builder options are unavailable. You may not have create permission.</section>;
  return <section className="mt-6 rounded-2xl border border-white/10 bg-[#09182d] p-5" aria-labelledby="builder-title"><header className="flex justify-between"><div><h2 id="builder-title" className="text-xl font-semibold">Create Agent</h2><p className="text-sm text-slate-400">Step {step+1} of {steps.length}: {steps[step]}</p></div><button aria-label="Close Agent Builder" onClick={close} className="focus-ring rounded-lg p-2"><X/></button></header>
    <ol className="mt-5 grid gap-2 sm:grid-cols-3 xl:grid-cols-6" aria-label="Builder progress">{steps.map((name,index)=><li key={name}><button type="button" onClick={()=>index<=step&&setStep(index)} aria-current={index===step?"step":undefined} className={`focus-ring flex w-full items-center gap-2 rounded-lg border p-2 text-left text-xs ${index===step?"border-violet-400 bg-violet-500/15":index<step?"border-emerald-500/30":"border-white/10"}`}><span className="grid h-6 w-6 place-items-center rounded-full bg-white/10">{index<step?<Check size={14}/>:index+1}</span>{name}</button></li>)}</ol>
    {general&&<p role="alert" className="mt-4 rounded-lg bg-red-500/10 p-3 text-red-200">{general}</p>}
    <div className="mt-6 min-h-64">{step===0&&<div className="grid gap-4 md:grid-cols-2"><Field label="Display name" required error={errors.name}><input className={field} value={form.name} onChange={e=>set("name",e.target.value)} aria-invalid={Boolean(errors.name)}/></Field><Field label="Stable slug"><input className={field} value={form.slug} onChange={e=>set("slug",e.target.value)}/></Field><Field label="Description"><textarea className={field} value={form.description} onChange={e=>set("description",e.target.value)}/></Field><Field label="Environments"><select multiple className={field} value={form.environments} onChange={e=>set("environments",Array.from(e.target.selectedOptions,option=>option.value))}><option>development</option><option>staging</option><option>production</option></select></Field></div>}
    {step===1&&<div className="grid gap-4 md:grid-cols-2"><Field label="Published instructions" required error={errors.instructions}><textarea className={`${field} min-h-40`} value={form.instructions} onChange={e=>set("instructions",e.target.value)} aria-invalid={Boolean(errors.instructions)}/></Field><div className="space-y-4"><Field label="Model"><select className={field} value={`${form.provider}:${form.model}`} onChange={e=>{const [provider,model]=e.target.value.split(":");setForm({...form,provider,model});}}>{options.models.map(item=><option key={`${item.provider}:${item.model}`} value={`${item.provider}:${item.model}`}>{item.label}</option>)}</select></Field><Field label="Planner"><select className={field} value={form.planner} onChange={e=>set("planner",e.target.value)}>{options.planners.map(item=><option key={item.name} value={item.name}>{item.label}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Maximum steps"><input type="number" min="1" max="100" className={field} value={form.maxSteps} onChange={e=>set("maxSteps",e.target.value)}/></Field><Field label="Timeout seconds"><input type="number" min="1" max="3600" className={field} value={form.timeout} onChange={e=>set("timeout",e.target.value)}/></Field></div></div></div>}
    {step===2&&<ChoiceGrid title="Authorized tools" items={options.tools} selected={form.tools} onToggle={name=>toggle("tools",name)} keyOf={item=>item.name} render={item=><><strong>{item.display_name}</strong><small>{item.provider} · {item.version} · {item.risk}</small></>}/>}{/* Tool assignments */}
    {step===3&&<ChoiceGrid title="Ready knowledge sources" items={options.knowledge} selected={form.knowledge} onToggle={id=>toggle("knowledge",id)} keyOf={item=>item.id} disabled={item=>item.readiness!=="ready"} render={item=><><strong>{item.name}</strong><small>{item.source_type} · {item.readiness} · {item.health}</small></>}/>}{/* Knowledge assignments */}
    {step===4&&<AccessEditor form={form} set={set} options={options}/>}{/* Access assignments */}
    {step===5&&<pre className="max-h-96 overflow-auto rounded-xl border border-white/10 bg-black/20 p-4 text-xs">{JSON.stringify({...payload,tools:form.tools,knowledge:form.knowledge,access:form.access},null,2)}</pre>}</div>
    <footer className="mt-5 flex flex-wrap justify-between gap-3 border-t border-white/10 pt-4"><button disabled={step===0} onClick={()=>move(-1)} className="focus-ring inline-flex items-center gap-2 rounded-lg border border-white/15 px-4 py-2 disabled:opacity-40"><ChevronLeft size={16}/>Back</button><div className="flex gap-2"><button disabled={saving} onClick={()=>save(false)} className="focus-ring rounded-lg border border-white/20 px-4 py-2">Save Draft</button>{step===steps.length-1?<button disabled={saving} onClick={()=>save(true)} className="focus-ring rounded-lg bg-violet-600 px-4 py-2">{saving?"Saving…":"Publish"}</button>:<button onClick={()=>move(1)} className="focus-ring inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2">Next<ChevronRight size={16}/></button>}</div></footer>
  </section>;
}

function Field({label,error,required,children}){return <label className="block text-sm">{label}{required&&<span aria-hidden="true"> *</span>}{children}{error&&<span className="mt-1 block text-xs text-red-300">{error}</span>}</label>}
function ChoiceGrid({title,items,selected,onToggle,keyOf,render,disabled=()=>false}){return <fieldset><legend className="mb-3 font-medium">{title}</legend><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map(item=>{const key=keyOf(item),off=disabled(item);return <label key={key} className={`flex min-h-20 items-center gap-3 rounded-xl border p-3 ${selected.includes(key)?"border-violet-400 bg-violet-500/10":"border-white/10"} ${off?"opacity-50":""}`}><input type="checkbox" disabled={off} checked={selected.includes(key)} onChange={()=>onToggle(key)}/><span className="flex flex-col">{render(item)}</span></label>})}</div></fieldset>}
function AccessEditor({form,set,options}){const [subjectType,setType]=useState("user"),[subjectId,setId]=useState(""),[action,setAction]=useState("view");const add=()=>{if(subjectId&&!form.access.some(item=>item.subject_type===subjectType&&item.subject_id===subjectId&&item.action===action))set("access",[...form.access,{subject_type:subjectType,subject_id:subjectId,action,enabled:true}]);setId("");};return <section><h3 className="font-medium">Access and governance</h3><p className="mt-1 text-sm text-slate-400">Platform permissions apply first. Explicit Agent assignments grant only the selected action; governance denies still take precedence.</p><div className="mt-4 grid gap-3 md:grid-cols-4"><select aria-label="Subject type" className={field} value={subjectType} onChange={e=>setType(e.target.value)}>{options.subject_types.map(item=><option key={item}>{item}</option>)}</select><input aria-label="Subject identifier" className={field} value={subjectId} onChange={e=>setId(e.target.value)} placeholder="user, group, role, or service ID"/><select aria-label="Access action" className={field} value={action} onChange={e=>setAction(e.target.value)}>{options.access_actions.map(item=><option key={item}>{item}</option>)}</select><button type="button" onClick={add} className="focus-ring mt-1 rounded-lg border border-white/20">Add assignment</button></div><ul className="mt-4 space-y-2">{form.access.map((item,index)=><li className="flex justify-between rounded-lg bg-white/5 p-3 text-sm" key={`${item.subject_type}:${item.subject_id}:${item.action}`}><span>{item.subject_type}: {item.subject_id} → {item.action}</span><button aria-label={`Remove ${item.subject_id} ${item.action}`} onClick={()=>set("access",form.access.filter((_,itemIndex)=>itemIndex!==index))}>Remove</button></li>)}</ul></section>}
