import {useMemo,useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {useNavigate} from "react-router-dom";
import {Search,SlidersHorizontal,ChevronLeft,ChevronRight,Wrench,Cloud,Folder,KeyRound} from "lucide-react";
import {getTools} from "../../services/tool.service";
const providerIcon={servicenow:Cloud,local_files:Folder,azure_blob:Cloud,azure_keyvault:KeyRound};
export default function ToolCatalogPage(){
 const nav=useNavigate(),[search,setSearch]=useState(""),[provider,setProvider]=useState(""),[category,setCategory]=useState(""),[enabled,setEnabled]=useState(""),[risk,setRisk]=useState(""),[page,setPage]=useState(1);
 const params=useMemo(()=>({search:search||undefined,provider:provider||undefined,category:category||undefined,enabled:enabled===""?undefined:enabled==="true",risk_level:risk||undefined,page,page_size:10}),[search,provider,category,enabled,risk,page]);
 const q=useQuery({queryKey:["tools",params],queryFn:()=>getTools(params)}),items=q.data?.items||[];
 const clear=()=>{setSearch("");setProvider("");setCategory("");setEnabled("");setRisk("");setPage(1)};
 return <section className="tool-shell"><div className="tool-heading"><div><h1>Tool Catalog</h1><p>Discover, configure, and run approved tools</p></div><button className="primary-button"><span>＋</span> Register tool</button></div>
 <div className="tool-filters"><label className="search-box"><Search size={16}/><input aria-label="Search tools" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search tools…"/></label>
 {[['Provider',provider,setProvider,['servicenow','local_files','azure_blob','azure_keyvault']],['Category',category,setCategory,['it_service_management','files','cloud_storage','secrets']],['Status',enabled,setEnabled,['true','false']],['Risk',risk,setRisk,['read','write','destructive']]].map(([label,value,set,options])=><label key={label} className="select-box"><span className="sr-only">{label}</span><select value={value} onChange={e=>{set(e.target.value);setPage(1)}}><option value="">{label}: All</option>{options.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label>)}
 <button className="clear-button" onClick={clear}>Clear filters</button></div>
 <div className="tool-table-wrap"><table className="tool-table"><thead><tr><th>Tool</th><th>Provider</th><th>Version</th><th>Status</th><th>Permissions</th><th>Risk</th><th>Readiness</th><th>Actions</th></tr></thead><tbody>
 {q.isLoading&&<tr><td colSpan="8"><div className="state-message">Loading approved tools…</div></td></tr>}
 {q.isError&&<tr><td colSpan="8"><div className="state-message error">Unable to load the catalog. {q.error?.response?.data?.detail?.message||"Try again."}</div></td></tr>}
 {!q.isLoading&&!q.isError&&!items.length&&<tr><td colSpan="8"><div className="state-message"><SlidersHorizontal/>No tools match these filters.</div></td></tr>}
 {items.map(tool=>{const Icon=providerIcon[tool.provider]||Wrench;return <tr key={`${tool.name}-${tool.version}`}><td><div className="tool-name"><span className="tool-icon"><Icon size={17}/></span><div><strong>{tool.display_name}</strong><small>{tool.name}</small><small>{tool.description}</small></div></div></td><td className="capitalize">{tool.provider.replaceAll('_',' ')}</td><td>v{tool.version}</td><td><span className={`status-pill ${tool.enabled?'success':'muted'}`}>{tool.enabled?'Enabled':'Disabled'}</span></td><td><code>{tool.permissions?.join(', ')}</code></td><td><span className="risk-pill">{tool.risk_level}</span></td><td><span className={`health-dot ${tool.configuration_state==='ready'?'ready':''}`}/>{tool.configuration_state.replaceAll('_',' ')}</td><td><button className="outline-button" onClick={()=>nav(`/tools/${tool.name}`)}>View details</button><button className="mini-button" onClick={()=>nav(`/tools/${tool.name}?tab=test`)}>Test</button></td></tr>})}
 </tbody></table><div className="table-footer"><span>Showing {items.length?((page-1)*10)+1:0} to {Math.min(page*10,q.data?.total||0)} of {q.data?.total||0} tools</span><div><button aria-label="Previous page" disabled={page===1} onClick={()=>setPage(x=>x-1)}><ChevronLeft size={16}/></button><span>{page}</span><button aria-label="Next page" disabled={page>=q.data?.pages} onClick={()=>setPage(x=>x+1)}><ChevronRight size={16}/></button></div></div></div></section>}
