import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {Link,useParams,useSearchParams} from "react-router-dom";
import {ArrowLeft,CheckCircle2,Copy,Play,Shield,Clock,Tag} from "lucide-react";
import {executeTool,getTool,setToolEnabled} from "../../services/tool.service";
function fieldDefault(schema){if(schema.default!==undefined)return schema.default;if(schema.type==='integer'||schema.type==='number')return '';if(schema.type==='boolean')return false;return ''}
function SchemaForm({schema,value,setValue}){return <div className="schema-form">{Object.entries(schema?.properties||{}).map(([name,field])=><label key={name}><span>{name.replaceAll('_',' ')} {schema.required?.includes(name)&&<b>*</b>}</span><small>{field.description}</small>{field.enum?<select value={value[name]??fieldDefault(field)} onChange={e=>setValue({...value,[name]:e.target.value})}><option value="">Select…</option>{field.enum.map(x=><option key={x}>{x}</option>)}</select>:field.type==='boolean'?<input type="checkbox" checked={!!value[name]} onChange={e=>setValue({...value,[name]:e.target.checked})}/>:<input type={field.type==='integer'||field.type==='number'?'number':'text'} min={field.minimum} max={field.maximum} value={value[name]??fieldDefault(field)} onChange={e=>setValue({...value,[name]:field.type==='integer'?Number(e.target.value):e.target.value})}/>}</label>)}</div>}
export default function ToolDetailsPage(){const{name}=useParams(),[params,setParams]=useSearchParams(),[input,setInput]=useState({}),qc=useQueryClient(),q=useQuery({queryKey:["tool",name],queryFn:()=>getTool(name)}),tool=q.data;
 const run=useMutation({mutationFn:()=>executeTool(name,input)}),toggle=useMutation({mutationFn:()=>setToolEnabled(name,tool.version,!tool.enabled),onSuccess:()=>qc.invalidateQueries({queryKey:["tool",name]})});const tab=params.get('tab')==='test'?'test':'overview';
 if(q.isLoading)return <section className="tool-shell"><div className="state-message">Loading tool…</div></section>;if(q.isError)return <section className="tool-shell"><div className="state-message error">Tool could not be loaded.</div></section>;
 return <section className="tool-shell"><Link to="/tools" className="back-link"><ArrowLeft size={14}/>Back to catalog</Link><div className="tool-heading"><div><h1>{tool.display_name}</h1><p>{tool.description}</p></div><div className="heading-actions"><button className="outline-button" onClick={()=>toggle.mutate()}>{tool.enabled?'Disable':'Enable'}</button><button className="primary-button" onClick={()=>setParams({tab:'test'})}><Play size={14}/>Test tool</button></div></div>
 <div className="detail-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setParams({})}>Overview</button><button className={tab==='test'?'active':''} onClick={()=>setParams({tab:'test'})}>Test Console</button><button>Versions</button><button>Activity</button></div>
 <div className="metadata-strip">{[[Shield,'Provider',tool.provider],[Tag,'Category',tool.category],[Tag,'Version',tool.version],[Shield,'Permission',tool.permissions.join(', ')],[Clock,'Timeout',`${tool.timeout_seconds}s`]].map(([Icon,label,val])=><div key={label}><Icon size={17}/><span><small>{label}</small><strong>{val}</strong></span></div>)}</div>
 {tab==='overview'?<div className="detail-grid"><article className="panel"><h2>Tool metadata</h2><dl>{[['Stable name',tool.name],['Owner',tool.author],['Risk',tool.risk_level],['Idempotent',tool.idempotent?'Yes':'No'],['Status',tool.enabled?'Enabled':'Disabled'],['Readiness',tool.health?.message||tool.configuration_state]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><h2>Tags</h2><div className="tags">{tool.tags.map(x=><span key={x}>{x}</span>)}</div></article><article className="panel"><h2>Input parameters</h2>{Object.entries(tool.parameters.properties).map(([k,v])=><div className="parameter-row" key={k}><code>{k}</code><span>{v.type}{tool.parameters.required?.includes(k)?' · required':''}</span></div>)}<h2>Recent executions</h2>{tool.recent_executions?.length?tool.recent_executions.map(x=><div className="execution-mini" key={x.execution_id}><span className={`status-pill ${x.status==='succeeded'?'success':'error'}`}>{x.status}</span><code>{x.execution_id.slice(0,8)}</code><span>{x.duration_ms} ms</span></div>):<p className="muted-text">No executions recorded yet.</p>}</article></div>:
 <div className="test-grid"><article className="panel"><h2>Input parameters</h2><SchemaForm schema={tool.parameters} value={input} setValue={setInput}/>{tool.parameters.required?.some(k=>input[k]===undefined||input[k]==='')&&<p role="alert" className="error-text">Complete all required parameters before running the tool.</p>}<button className="run-button" disabled={run.isPending||!tool.enabled||tool.parameters.required?.some(k=>input[k]===undefined||input[k]==='')} onClick={()=>run.mutate()}><Play size={15}/>{run.isPending?'Running…':'Run test'}</button></article><article className="panel result-panel"><h2>Test result</h2>{!run.data&&!run.error?<div className="result-empty">Run the tool to inspect its normalized response.</div>:run.error?<div className="result-error">{run.error.response?.data?.detail?.message||run.error.message}</div>:<><div className={`result-status ${run.data.status==='succeeded'?'success':'error'}`}>{run.data.status==='succeeded'&&<CheckCircle2 size={17}/>}<strong>{run.data.status}</strong><span>Execution ID {run.data.execution_id}</span><span>{run.data.meta.duration_ms} ms</span></div><div className="code-result"><button onClick={()=>navigator.clipboard.writeText(JSON.stringify(run.data,null,2))}><Copy size={14}/>Copy</button><pre>{JSON.stringify(run.data,null,2)}</pre></div></>}</article></div>}</section>}
